Downloading file to validate.
File download complete
Temporary downloaded file deleted
Traceback (most recent call last):
  File "/app/acc_native_jobs/__init__.py", line 42, in wrapper_func
    func(*args, **kwargs)
  File "/app/acc_native_jobs/__init__.py", line 65, in verify_csv_regional_timeseries
    csv_regional_timeseries_verification_service()
  File "/app/acc_native_jobs/validate_csv_regional_timeseries.py", line 289, in __call__
    self.create_validated_file()
  File "/app/acc_native_jobs/validate_csv_regional_timeseries.py", line 265, in create_validated_file
    for row in validated_rows:
  File "/app/acc_native_jobs/validate_csv_regional_timeseries.py", line 219, in get_validated_rows
    row = self.validate_row_data(row)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/acc_native_jobs/validate_csv_regional_timeseries.py", line 161, in validate_row_data
    if len(self.harvest_count[key]) <= 200: #limit harvest
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'CsvRegionalTimeseriesVerificationService' object has no attribute 'harvest_count'
